In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
DATA_PATH = r"E:\Reel-Recommendation-Engine\data\raw"

USER_FILE = DATA_PATH + r"\user_features_pure.csv"
VIDEO_BASIC_FILE = DATA_PATH + r"\video_features_basic_pure.csv"
VIDEO_STATS_FILE = DATA_PATH + r"\video_features_statistic_pure.csv"

LOG_STD_1 = DATA_PATH + r"\log_standard_4_08_to_4_21_pure.csv"
LOG_STD_2 = DATA_PATH + r"\log_standard_4_22_to_5_08_pure.csv"

LOG_RANDOM = DATA_PATH + r"\log_random_4_22_to_5_08_pure.csv"

print("Paths Created Successfully")

Paths Created Successfully

In [3]:
import os

print("User File:", os.path.exists(USER_FILE))
print("Video Basic File:", os.path.exists(VIDEO_BASIC_FILE))
print("Video Stats File:", os.path.exists(VIDEO_STATS_FILE))
print("Log Std 1:", os.path.exists(LOG_STD_1))
print("Log Std 2:", os.path.exists(LOG_STD_2))
print("Log Random:", os.path.exists(LOG_RANDOM))

User File: True
Video Basic File: True
Video Stats File: True
Log Std 1: True
Log Std 2: True
Log Random: True

In [4]:
users_df = pd.read_csv(USER_FILE)

video_basic_df = pd.read_csv(VIDEO_BASIC_FILE)

video_stats_df = pd.read_csv(VIDEO_STATS_FILE)

log_std1_df = pd.read_csv(LOG_STD_1)

log_std2_df = pd.read_csv(LOG_STD_2)

log_random_df = pd.read_csv(LOG_RANDOM)

print("All Datasets Loaded Successfully")

All Datasets Loaded Successfully

In [5]:
print("="*60)

print("Users Shape:", users_df.shape)

print("Video Basic Shape:", video_basic_df.shape)

print("Video Statistics Shape:", video_stats_df.shape)

print("Log Standard 1 Shape:", log_std1_df.shape)

print("Log Standard 2 Shape:", log_std2_df.shape)

print("Log Random Shape:", log_random_df.shape)

============================================================
Users Shape: (27285, 31)
Video Basic Shape: (7583, 12)
Video Statistics Shape: (7583, 52)
Log Standard 1 Shape: (1141112, 19)
Log Standard 2 Shape: (295497, 19)
Log Random Shape: (1186059, 19)

In [6]:
datasets = {
    "Users": users_df,
    "Video Basic": video_basic_df,
    "Video Statistics": video_stats_df,
    "Log Standard 1": log_std1_df,
    "Log Standard 2": log_std2_df,
    "Log Random": log_random_df
}

for name, df in datasets.items():

    print("\n" + "="*100)
    print(name)
    print("="*100)

    print(df.columns.tolist())

====================================================================================================
Users
====================================================================================================
['user_id', 'user_active_degree', 'is_lowactive_period', 'is_live_streamer', 'is_video_author', 'follow_user_num', 'follow_user_num_range', 'fans_user_num', 'fans_user_num_range', 'friend_user_num', 'friend_user_num_range', 'register_days', 'register_days_range', 'onehot_feat0', 'onehot_feat1', 'onehot_feat2', 'onehot_feat3', 'onehot_feat4', 'onehot_feat5', 'onehot_feat6', 'onehot_feat7', 'onehot_feat8', 'onehot_feat9', 'onehot_feat10', 'onehot_feat11', 'onehot_feat12', 'onehot_feat13', 'onehot_feat14', 'onehot_feat15', 'onehot_feat16', 'onehot_feat17']

====================================================================================================
Video Basic
====================================================================================================
['video_id', 'author_id', 'video_type', 'upload_dt', 'upload_type', 'visible_status', 'video_duration', 'server_width', 'server_height', 'music_id', 'music_type', 'tag']

====================================================================================================
Video Statistics
====================================================================================================
['video_id', 'counts', 'show_cnt', 'show_user_num', 'play_cnt', 'play_user_num', 'play_duration', 'complete_play_cnt', 'complete_play_user_num', 'valid_play_cnt', 'valid_play_user_num', 'long_time_play_cnt', 'long_time_play_user_num', 'short_time_play_cnt', 'short_time_play_user_num', 'play_progress', 'comment_stay_duration', 'like_cnt', 'like_user_num', 'click_like_cnt', 'double_click_cnt', 'cancel_like_cnt', 'cancel_like_user_num', 'comment_cnt', 'comment_user_num', 'direct_comment_cnt', 'reply_comment_cnt', 'delete_comment_cnt', 'delete_comment_user_num', 'comment_like_cnt', 'comment_like_user_num', 'follow_cnt', 'follow_user_num', 'cancel_follow_cnt', 'cancel_follow_user_num', 'share_cnt', 'share_user_num', 'download_cnt', 'download_user_num', 'report_cnt', 'report_user_num', 'reduce_similar_cnt', 'reduce_similar_user_num', 'collect_cnt', 'collect_user_num', 'cancel_collect_cnt', 'cancel_collect_user_num', 'direct_comment_user_num', 'reply_comment_user_num', 'share_all_cnt', 'share_all_user_num', 'outsite_share_all_cnt']

====================================================================================================
Log Standard 1
====================================================================================================
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']

====================================================================================================
Log Standard 2
====================================================================================================
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']

====================================================================================================
Log Random
====================================================================================================
['user_id', 'video_id', 'date', 'hourmin', 'time_ms', 'is_click', 'is_like', 'is_follow', 'is_comment', 'is_forward', 'is_hate', 'long_view', 'play_time_ms', 'duration_ms', 'profile_stay_time', 'comment_stay_time', 'is_profile_enter', 'is_rand', 'tab']

In [7]:
for name, df in datasets.items():

    print("\n" + "="*100)
    print(name)
    print("="*100)

    missing = df.isnull().sum()

    missing = missing[missing > 0]

    print(missing.sort_values(ascending=False).head(20))

====================================================================================================
Users
====================================================================================================
onehot_feat4     874
onehot_feat12    714
onehot_feat13    714
onehot_feat14    714
onehot_feat15    714
onehot_feat16    714
onehot_feat17    714
dtype: int64

====================================================================================================
Video Basic
====================================================================================================
video_duration    239
music_type        203
tag                96
dtype: int64

====================================================================================================
Video Statistics
====================================================================================================
Series([], dtype: int64)

====================================================================================================
Log Standard 1
====================================================================================================
Series([], dtype: int64)

====================================================================================================
Log Standard 2
====================================================================================================
Series([], dtype: int64)

====================================================================================================
Log Random
====================================================================================================
Series([], dtype: int64)

In [8]:
for name, df in datasets.items():

    print("\n" + "="*100)
    print(name)
    print("="*100)

    print(df.info())

====================================================================================================
Users
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27285 entries, 0 to 27284
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                27285 non-null  int64
 1   user_active_degree     27285 non-null  object
 2   is_lowactive_period    27285 non-null  int64
 3   is_live_streamer       27285 non-null  int64
 4   is_video_author        27285 non-null  int64
 5   follow_user_num        27285 non-null  int64
 6   follow_user_num_range  27285 non-null  object
 7   fans_user_num          27285 non-null  int64
 8   fans_user_num_range    27285 non-null  object
 9   friend_user_num        27285 non-null  int64
 10  friend_user_num_range  27285 non-null  object
 11  register_days          27285 non-null  int64
 12  register_days_range    27285 non-null  object
 13  onehot_feat0           27285 non-null  int64
 14  onehot_feat1           27285 non-null  int64
 15  onehot_feat2           27285 non-null  int64
 16  onehot_feat3           27285 non-null  int64
 17  onehot_feat4           26411 non-null  float64
 18  onehot_feat5           27285 non-null  int64
 19  onehot_feat6           27285 non-null  int64
 20  onehot_feat7           27285 non-null  int64
 21  onehot_feat8           27285 non-null  int64
 22  onehot_feat9           27285 non-null  int64
 23  onehot_feat10          27285 non-null  int64
 24  onehot_feat11          27285 non-null  int64
 25  onehot_feat12          26571 non-null  float64
 26  onehot_feat13          26571 non-null  float64
 27  onehot_feat14          26571 non-null  float64
 28  onehot_feat15          26571 non-null  float64
 29  onehot_feat16          26571 non-null  float64
 30  onehot_feat17          26571 non-null  float64
dtypes: float64(7), int64(19), object(5)
memory usage: 6.5+ MB
None

====================================================================================================
Video Basic
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7583 entries, 0 to 7582
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   video_id        7583 non-null   int64
 1   author_id       7583 non-null   int64
 2   video_type      7583 non-null   object
 3   upload_dt       7583 non-null   object
 4   upload_type     7583 non-null   object
 5   visible_status  7583 non-null   float64
 6   video_duration  7344 non-null   float64
 7   server_width    7583 non-null   float64
 8   server_height   7583 non-null   float64
 9   music_id        7583 non-null   int64
 10  music_type      7380 non-null   float64
 11  tag             7487 non-null   object
dtypes: float64(5), int64(3), object(4)
memory usage: 711.0+ KB
None

====================================================================================================
Video Statistics
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7583 entries, 0 to 7582
Data columns (total 52 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   video_id                  7583 non-null   int64
 1   counts                    7583 non-null   int64
 2   show_cnt                  7583 non-null   float64
 3   show_user_num             7583 non-null   float64
 4   play_cnt                  7583 non-null   float64
 5   play_user_num             7583 non-null   float64
 6   play_duration             7583 non-null   float64
 7   complete_play_cnt         7583 non-null   float64
 8   complete_play_user_num    7583 non-null   float64
 9   valid_play_cnt            7583 non-null   float64
 10  valid_play_user_num       7583 non-null   float64
 11  long_time_play_cnt        7583 non-null   float64
 12  long_time_play_user_num   7583 non-null   float64
 13  short_time_play_cnt       7583 non-null   float64
 14  short_time_play_user_num  7583 non-null   float64
 15  play_progress             7583 non-null   float64
 16  comment_stay_duration     7583 non-null   float64
 17  like_cnt                  7583 non-null   float64
 18  like_user_num             7583 non-null   float64
 19  click_like_cnt            7583 non-null   float64
 20  double_click_cnt          7583 non-null   float64
 21  cancel_like_cnt           7583 non-null   float64
 22  cancel_like_user_num      7583 non-null   float64
 23  comment_cnt               7583 non-null   float64
 24  comment_user_num          7583 non-null   float64
 25  direct_comment_cnt        7583 non-null   float64
 26  reply_comment_cnt         7583 non-null   float64
 27  delete_comment_cnt        7583 non-null   float64
 28  delete_comment_user_num   7583 non-null   float64
 29  comment_like_cnt          7583 non-null   float64
 30  comment_like_user_num     7583 non-null   float64
 31  follow_cnt                7583 non-null   float64
 32  follow_user_num           7583 non-null   float64
 33  cancel_follow_cnt         7583 non-null   float64
 34  cancel_follow_user_num    7583 non-null   float64
 35  share_cnt                 7583 non-null   float64
 36  share_user_num            7583 non-null   float64
 37  download_cnt              7583 non-null   float64
 38  download_user_num         7583 non-null   float64
 39  report_cnt                7583 non-null   float64
 40  report_user_num           7583 non-null   float64
 41  reduce_similar_cnt        7583 non-null   float64
 42  reduce_similar_user_num   7583 non-null   float64
 43  collect_cnt               7583 non-null   float64
 44  collect_user_num          7583 non-null   float64
 45  cancel_collect_cnt        7583 non-null   float64
 46  cancel_collect_user_num   7583 non-null   float64
 47  direct_comment_user_num   7583 non-null   float64
 48  reply_comment_user_num    7583 non-null   float64
 49  share_all_cnt             7583 non-null   float64
 50  share_all_user_num        7583 non-null   float64
 51  outsite_share_all_cnt     7583 non-null   float64
dtypes: float64(50), int64(2)
memory usage: 3.0 MB
None

====================================================================================================
Log Standard 1
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1141112 entries, 0 to 1141111
Data columns (total 19 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   user_id            1141112 non-null  int64
 1   video_id           1141112 non-null  int64
 2   date               1141112 non-null  int64
 3   hourmin            1141112 non-null  int64
 4   time_ms            1141112 non-null  int64
 5   is_click           1141112 non-null  int64
 6   is_like            1141112 non-null  int64
 7   is_follow          1141112 non-null  int64
 8   is_comment         1141112 non-null  int64
 9   is_forward         1141112 non-null  int64
 10  is_hate            1141112 non-null  int64
 11  long_view          1141112 non-null  int64
 12  play_time_ms       1141112 non-null  int64
 13  duration_ms        1141112 non-null  int64
 14  profile_stay_time  1141112 non-null  int64
 15  comment_stay_time  1141112 non-null  int64
 16  is_profile_enter   1141112 non-null  int64
 17  is_rand            1141112 non-null  int64
 18  tab                1141112 non-null  int64
dtypes: int64(19)
memory usage: 165.4 MB
None

====================================================================================================
Log Standard 2
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295497 entries, 0 to 295496
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   user_id            295497 non-null  int64
 1   video_id           295497 non-null  int64
 2   date               295497 non-null  int64
 3   hourmin            295497 non-null  int64
 4   time_ms            295497 non-null  int64
 5   is_click           295497 non-null  int64
 6   is_like            295497 non-null  int64
 7   is_follow          295497 non-null  int64
 8   is_comment         295497 non-null  int64
 9   is_forward         295497 non-null  int64
 10  is_hate            295497 non-null  int64
 11  long_view          295497 non-null  int64
 12  play_time_ms       295497 non-null  int64
 13  duration_ms        295497 non-null  int64
 14  profile_stay_time  295497 non-null  int64
 15  comment_stay_time  295497 non-null  int64
 16  is_profile_enter   295497 non-null  int64
 17  is_rand            295497 non-null  int64
 18  tab                295497 non-null  int64
dtypes: int64(19)
memory usage: 42.8 MB
None

====================================================================================================
Log Random
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186059 entries, 0 to 1186058
Data columns (total 19 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   user_id            1186059 non-null  int64
 1   video_id           1186059 non-null  int64
 2   date               1186059 non-null  int64
 3   hourmin            1186059 non-null  int64
 4   time_ms            1186059 non-null  int64
 5   is_click           1186059 non-null  int64
 6   is_like            1186059 non-null  int64
 7   is_follow          1186059 non-null  int64
 8   is_comment         1186059 non-null  int64
 9   is_forward         1186059 non-null  int64
 10  is_hate            1186059 non-null  int64
 11  long_view          1186059 non-null  int64
 12  play_time_ms       1186059 non-null  int64
 13  duration_ms        1186059 non-null  int64
 14  profile_stay_time  1186059 non-null  int64
 15  comment_stay_time  1186059 non-null  int64
 16  is_profile_enter   1186059 non-null  int64
 17  is_rand            1186059 non-null  int64
 18  tab                1186059 non-null  int64
dtypes: int64(19)
memory usage: 171.9 MB
None

In [9]:
train_logs_df = pd.concat(
    [log_std1_df, log_std2_df],
    ignore_index=True
)

print("Training Logs Shape:")
print(train_logs_df.shape)

Training Logs Shape:
(1436609, 19)

In [10]:
print("Users Duplicates:",
      users_df.duplicated().sum())

print("Video Basic Duplicates:",
      video_basic_df.duplicated().sum())

print("Video Statistics Duplicates:",
      video_stats_df.duplicated().sum())

print("Training Logs Duplicates:",
      train_logs_df.duplicated().sum())

Users Duplicates: 0
Video Basic Duplicates: 0
Video Statistics Duplicates: 0
Training Logs Duplicates: 21987

In [11]:
user_missing_cols = [
    'onehot_feat4',
    'onehot_feat12',
    'onehot_feat13',
    'onehot_feat14',
    'onehot_feat15',
    'onehot_feat16',
    'onehot_feat17'
]

for col in user_missing_cols:
    users_df[col] = users_df[col].fillna(-1)

In [12]:
video_basic_df['video_duration'] = video_basic_df['video_duration'].fillna(
    video_basic_df['video_duration'].median()
)

video_basic_df['music_type'] = video_basic_df['music_type'].fillna(-1)

video_basic_df['tag'] = video_basic_df['tag'].fillna("unknown")

In [13]:
print("Users Missing:")
print(users_df.isnull().sum().sum())

print("Video Basic Missing:")
print(video_basic_df.isnull().sum().sum())

print("Video Statistics Missing:")
print(video_stats_df.isnull().sum().sum())

print("Training Logs Missing:")
print(train_logs_df.isnull().sum().sum())

Users Missing:
0
Video Basic Missing:
0
Video Statistics Missing:
0
Training Logs Missing:
0

In [14]:
train_logs_df["watch_ratio"] = (
    train_logs_df["play_time_ms"] /
    train_logs_df["duration_ms"]
)

train_logs_df["watch_ratio"] = (
    train_logs_df["watch_ratio"]
    .clip(0, 1)
)

In [15]:
train_logs_df["engagement_score"] = (

      train_logs_df["is_like"] * 3

    + train_logs_df["is_comment"] * 4

    + train_logs_df["is_follow"] * 5

    + train_logs_df["is_forward"] * 4

    + train_logs_df["is_profile_enter"] * 2

    + train_logs_df["long_view"] * 2

    - train_logs_df["is_hate"] * 5

)

In [16]:
train_logs_df["interaction_score"] = (

      train_logs_df["watch_ratio"] * 5

    + train_logs_df["engagement_score"]

)

In [17]:
train_logs_df[
    [
        "watch_ratio",
        "engagement_score",
        "interaction_score"
    ]
].describe()

        watch_ratio  engagement_score  interaction_score
count  1.431626e+06      1.436609e+06       1.431626e+06
mean   3.311377e-01      7.840679e-01       2.442466e+00
std    3.923235e-01      1.217405e+00       2.937576e+00
min    0.000000e+00     -5.000000e+00      -5.000000e+00
25%    1.722817e-02      0.000000e+00       8.763694e-02
50%    1.063813e-01      0.000000e+00       5.957263e-01
75%    6.949917e-01      2.000000e+00       5.000000e+00
max    1.000000e+00      1.600000e+01       2.100000e+01

In [18]:
print("Before:", train_logs_df.shape)

train_logs_df = train_logs_df.drop_duplicates()

print("After:", train_logs_df.shape)

Before: (1436609, 22)
After: (1414622, 22)

In [19]:
user_activity = train_logs_df.groupby("user_id").agg({

    "video_id":"count",

    "watch_ratio":"mean",

    "engagement_score":"mean"

}).reset_index()

In [20]:
user_activity.columns = [

    "user_id",

    "total_interactions",

    "avg_watch_ratio",

    "avg_engagement"

]

In [21]:
user_activity["user_activity_score"] = (

      user_activity["total_interactions"] * 0.5

    + user_activity["avg_watch_ratio"] * 50

    + user_activity["avg_engagement"] * 10

)

In [22]:
user_activity.head()

,user_id,total_interactions,avg_watch_ratio,avg_engagement,user_activity_score
0,0,13,0.093034,0.153846,12.690148
1,1,13,0.560065,1.307692,47.580157
2,2,114,0.499046,0.964912,91.601430
3,3,54,0.298638,0.740741,49.339303
4,4,26,0.301552,0.615385,34.231462

In [23]:
video_stats_df["video_popularity_score"] = (

      video_stats_df["play_cnt"] * 0.20

    + video_stats_df["like_cnt"] * 0.30

    + video_stats_df["comment_cnt"] * 0.20

    + video_stats_df["share_cnt"] * 0.15

    + video_stats_df["follow_cnt"] * 0.15

)

In [24]:
video_stats_df[
    [
        "video_id",
        "video_popularity_score"
    ]
].head()

   video_id  video_popularity_score
0         0              165.492157
1         1              436.037132
2         2               87.451099
3         3              189.684722
4         4             1010.691011

In [25]:
creator_stats = (

    video_basic_df[["video_id","author_id"]]

    .merge(

        video_stats_df[
            [
                "video_id",
                "video_popularity_score"
            ]
        ],

        on="video_id",

        how="left"

    )
)

In [26]:
creator_score = (

    creator_stats

    .groupby("author_id")

    ["video_popularity_score"]

    .mean()

    .reset_index()

)

In [27]:
creator_score.columns = [

    "author_id",

    "creator_score"

]

In [28]:
creator_score.head()

   author_id  creator_score
0          0   22056.179448
1        161    1013.010959
2        510     279.285028
3        534    1775.472024
4        566     279.694333

In [29]:
recommendation_dataset = train_logs_df.merge(

    users_df,

    on="user_id",

    how="left"

)

In [30]:
print(recommendation_dataset.shape)

(1414622, 52)

In [31]:
recommendation_dataset = recommendation_dataset.merge(

    video_basic_df,

    on="video_id",

    how="left"

)

In [32]:
print(recommendation_dataset.shape)

(1414622, 63)

In [33]:
recommendation_dataset = recommendation_dataset.merge(

    video_stats_df,

    on="video_id",

    how="left"

)

In [34]:
print(recommendation_dataset.shape)

(1414622, 115)

In [35]:
recommendation_dataset = recommendation_dataset.merge(

    user_activity[
        [
            "user_id",
            "user_activity_score"
        ]
    ],

    on="user_id",

    how="left"

)

In [36]:
recommendation_dataset = recommendation_dataset.merge(

    creator_score,

    on="author_id",

    how="left"

)

In [37]:
print("Final Dataset Shape:")

print(recommendation_dataset.shape)

Final Dataset Shape:
(1414622, 117)

In [38]:
recommendation_dataset["recommendation_score"] = (

      recommendation_dataset["watch_ratio"] * 0.30

    + recommendation_dataset["engagement_score"] * 0.25

    + recommendation_dataset["user_activity_score"] * 0.15

    + recommendation_dataset["video_popularity_score"] * 0.15

    + recommendation_dataset["creator_score"] * 0.15

)

In [39]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

recommendation_dataset["recommendation_score"] = scaler.fit_transform(
    recommendation_dataset[["recommendation_score"]]
)

In [40]:
recommendation_dataset["recommendation_score"].describe()

count    1.409646e+06
mean     8.754370e-02
std      1.386591e-01
min      0.000000e+00
25%      1.471320e-02
50%      3.793040e-02
75%      9.398604e-02
max      1.000000e+00
Name: recommendation_score, dtype: float64

In [41]:
user_features = recommendation_dataset.groupby("user_id").agg({

    "watch_ratio":"mean",

    "engagement_score":"mean",

    "recommendation_score":"mean",

    "user_activity_score":"mean"

}).reset_index()

In [42]:
user_features.head()

,user_id,watch_ratio,engagement_score,recommendation_score,user_activity_score
0,0,0.093034,0.153846,0.130750,12.690148
1,1,0.560065,1.307692,0.046964,47.580157
2,2,0.499046,0.964912,0.090811,91.601430
3,3,0.298638,0.740741,0.084469,49.339303
4,4,0.301552,0.615385,0.069042,34.231462

In [43]:
print(user_features.shape)

(27077, 5)

In [44]:
video_features = recommendation_dataset.groupby("video_id").agg({

    "watch_ratio":"mean",

    "engagement_score":"mean",

    "recommendation_score":"mean",

    "video_popularity_score":"mean"

}).reset_index()

In [45]:
video_features.head()

,video_id,watch_ratio,engagement_score,recommendation_score,video_popularity_score
0,0,0.006822,0.000000,0.001657,165.492157
1,1,0.048138,0.250000,0.004052,436.037132
2,2,0.257812,0.250000,0.000884,87.451099
3,3,0.213412,0.000000,0.002532,189.684722
4,4,0.493835,1.076923,0.009545,1010.691011

In [46]:
print(video_features.shape)

(7551, 5)

In [47]:
import os

os.makedirs(
    r"E:\Reel-Recommendation-Engine\data\processed",
    exist_ok=True
)

In [48]:
users_df.to_csv(
    r"E:\Reel-Recommendation-Engine\data\processed\users_cleaned.csv",
    index=False
)

video_basic_df.to_csv(
    r"E:\Reel-Recommendation-Engine\data\processed\videos_cleaned.csv",
    index=False
)

train_logs_df.to_csv(
    r"E:\Reel-Recommendation-Engine\data\processed\interactions_cleaned.csv",
    index=False
)

recommendation_dataset.to_csv(
    r"E:\Reel-Recommendation-Engine\data\processed\recommendation_dataset.csv",
    index=False
)

user_features.to_csv(
    r"E:\Reel-Recommendation-Engine\data\processed\user_features.csv",
    index=False
)

video_features.to_csv(
    r"E:\Reel-Recommendation-Engine\data\processed\video_features.csv",
    index=False
)

print("All Processed Files Saved Successfully")

All Processed Files Saved Successfully

In [49]:
print("Users:", users_df.shape)

print("Videos:", video_basic_df.shape)

print("Interactions:", train_logs_df.shape)

print("Recommendation Dataset:", recommendation_dataset.shape)

print("User Features:", user_features.shape)

print("Video Features:", video_features.shape)

Users: (27285, 31)
Videos: (7583, 12)
Interactions: (1414622, 22)
Recommendation Dataset: (1414622, 118)
User Features: (27077, 5)
Video Features: (7551, 5)

In [50]:
import os

processed_path = r"E:\Reel-Recommendation-Engine\data\processed"

print(os.listdir(processed_path))

['interactions_cleaned.csv', 'recommendation_dataset.csv', 'users_cleaned.csv', 'user_features.csv', 'videos_cleaned.csv', 'video_features.csv']

In [51]:
video_stats_df.to_csv(
    r"E:\Reel-Recommendation-Engine\data\processed\video_statistics_cleaned.csv",
    index=False
)

print("Video Statistics Saved")

Video Statistics Saved